# Generated by Django 2.1.2 on 2018-10-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20181015_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='More',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicesHeader',
        ),
        migrations.DeleteModel(
            name='Showcase',
        ),
    ]
