# Generated by Django 2.1.2 on 2018-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20181016_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('tp', 'Title Page'), ('sv', 'Services'), ('wu', 'Why Us'), ('cr', 'Careers'), ('au', 'About Us')], default='tp', max_length=2),
        ),
    ]
