# Generated by Django 2.1.2 on 2018-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_auto_20181016_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('Title Page', 'Title Page'), ('Services', 'Services'), ('Why Us', 'Why Us'), ('Careers', 'Careers'), ('About Us', 'About Us')], default='Title Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
