# Generated by Django 2.1.2 on 2018-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20181016_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('Title Page', 'Title Page'), ('Services Header', 'Services Header'), ('Services', 'Services'), ('Why Us', 'Why Us'), ('Careers', 'Careers'), ('About Us', 'About Us')], default='Title Page', max_length=15),
        ),
    ]
