# Generated by Django 2.1.2 on 2018-10-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20181016_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('Title Page', 'Title Page'), ('Services Header', 'Services Header'), ('Service 1', 'Service 1'), ('Service 2', 'Service 2'), ('Service 3', 'Service 3'), ('Why Us', 'Why Us'), ('Careers', 'Careers'), ('About Us', 'About Us')], default='Title Page', max_length=15),
        ),
    ]
