# Generated by Django 2.1.2 on 2018-10-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_auto_20181017_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('Title Page', 'Title Page'), ('Services Header', 'Services Header'), ('Services', 'Services'), ('Why Us', 'Why Us'), ('Careers', 'Careers'), ('About Us', 'About Us')], default='Title Page', max_length=15),
        ),
    ]
