# Generated by Django 2.1.2 on 2018-10-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_auto_20181018_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Service 1', 'Service 1'), ('Service 2', 'Service 2'), ('Service 3', 'Service 3'), ('Service 1 Home', 'Service 1 Home'), ('Service 2 Home', 'Service 2 Home'), ('Service 3 Home', 'Service 3 Home')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(choices=[('Title Page', 'Title Page'), ('Services Header', 'Services Header'), ('Services', 'Services'), ('Why Us', 'Why Us'), ('Careers', 'Careers'), ('About Us', 'About Us')], max_length=15),
        ),
    ]
