# Generated by Django 2.1.2 on 2018-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20181019_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Service 1', 'Service 1'), ('Service 2', 'Service 2'), ('Service 3', 'Service 3'), ('Service 1 Home', 'Service 1 Home'), ('Service 2 Home', 'Service 2 Home'), ('Service 3 Home', 'Service 3 Home')], max_length=20)),
                ('icon', models.CharField(choices=[('laptop', 'fas fa-laptop'), ('user', 'fas fa-user')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
