# Generated by Django 2.1.2 on 2018-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_auto_20181019_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Services', 'Services'), ('Services Home', 'Services Home')], max_length=20),
        ),
    ]
