# Generated by Django 2.1.2 on 2018-10-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_auto_20181019_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fas fa-laptop', 'laptop'), ('fas fa-user', 'user')], max_length=20),
        ),
    ]
