# Generated by Django 2.1.2 on 2018-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_auto_20181019_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fas fa-laptop-code', 'Laptop'), ('fas fa-user', 'User'), ('fas fa-network-wired', 'Network'), ('fas fa-globe-americas', 'Globe'), ('fas fa-layer-group', 'Layer'), ('fas fa-chart-pie', 'Pie Chart'), ('fas fa-chart-line', 'Line Chart')], max_length=20),
        ),
    ]
